networks:
  app-network:
    driver: bridge

services:
  backend:
    image: hojiakbar2806/my-portfolio-backend
    container_name: portfolio-backend
    command: /bin/sh -c "alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 main:app"
    environment:
      - PY_ENV=production
      - DEBUG=False
    env_file:
      - .env  
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    image: hojiakbar2806/my-portfolio-frontend
    container_name: portfolio-frontend
    environment:
      - NODE_ENV=production
    env_file:
      - .env  
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    depends_on:
      - portfolio-frontend
      - portfolio-backend
    ports:
      - "82:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./nginx/error-pages:/usr/share/nginx/html  
    networks:
      - app-network