name: M-Look frontend deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            --cache-from hojiakbar2806/my-portfolio-frontend:latest \
            --tag hojiakbar2806/my-portfolio-frontend:latest ./frontend

      - name: Push Docker Image
        run: docker push hojiakbar2806/my-portfolio-frontend:latest

    #   - name: Deploy to AWS
    #     run: |
    #       echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
    #       chmod 600 ~/ssh_key

    #       ssh -o StrictHostKeyChecking=no -i "~/ssh_key" ubuntu@13.53.95.28 << 'EOF'
    #         cd ~/m-look

    #         git pull -f origin main

    #         sudo rm -rf m-look-front m-look-back .github

    #         sudo docker pull hojiakbar2806/my-portfolio-frontend:latest

    #         sudo docker-compose stop frontend
    #         sudo docker-compose rm -f frontend
    #         sudo docker-compose up -d frontend

    #         sudo docker image prune -f
    #         sudo docker container prune -f
    #       EOF
